// <auto-generated />
using JoiDelivery.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JoiDelivery.Migrations
{
    [DbContext(typeof(JoiDbContext))]
    partial class JoiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.12");

            modelBuilder.Entity("JoiDelivery.Domain.Entities.Cart", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("OutletId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OutletId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("JoiDelivery.Domain.Entities.Outlet", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Outlets");

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("JoiDelivery.Domain.Entities.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<float>("MaxRecommendedPrice")
                        .HasColumnType("REAL")
                        .HasColumnName("MaxRecommendedPrice");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("JoiDelivery.Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("JoiDelivery.Domain.Entities.GroceryStore", b =>
                {
                    b.HasBaseType("JoiDelivery.Domain.Entities.Outlet");

                    b.ToTable("GroceryStores");
                });

            modelBuilder.Entity("JoiDelivery.Domain.Entities.Restaurant", b =>
                {
                    b.HasBaseType("JoiDelivery.Domain.Entities.Outlet");

                    b.ToTable("Restaurants");
                });

            modelBuilder.Entity("JoiDelivery.Domain.Entities.FoodProduct", b =>
                {
                    b.HasBaseType("JoiDelivery.Domain.Entities.Product");

                    b.ToTable("FoodProduct", (string)null);
                });

            modelBuilder.Entity("JoiDelivery.Domain.Entities.GroceryProduct", b =>
                {
                    b.HasBaseType("JoiDelivery.Domain.Entities.Product");

                    b.Property<int>("AvailableStock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CartId")
                        .HasColumnType("TEXT");

                    b.Property<float>("Discount")
                        .HasColumnType("REAL");

                    b.Property<int>("ExpiryDate")
                        .HasColumnType("INTEGER");

                    b.Property<float>("SellingPrice")
                        .HasColumnType("REAL");

                    b.Property<string>("StoreId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Threshold")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Weight")
                        .HasColumnType("REAL");

                    b.HasIndex("CartId");

                    b.HasIndex("StoreId");

                    b.ToTable("GroceryProduct", (string)null);
                });

            modelBuilder.Entity("JoiDelivery.Domain.Entities.Cart", b =>
                {
                    b.HasOne("JoiDelivery.Domain.Entities.Outlet", "Outlet")
                        .WithMany()
                        .HasForeignKey("OutletId");

                    b.HasOne("JoiDelivery.Domain.Entities.User", "User")
                        .WithOne("Cart")
                        .HasForeignKey("JoiDelivery.Domain.Entities.Cart", "UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Outlet");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JoiDelivery.Domain.Entities.GroceryProduct", b =>
                {
                    b.HasOne("JoiDelivery.Domain.Entities.Cart", null)
                        .WithMany("Products")
                        .HasForeignKey("CartId");

                    b.HasOne("JoiDelivery.Domain.Entities.GroceryStore", "Store")
                        .WithMany("Inventory")
                        .HasForeignKey("StoreId");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("JoiDelivery.Domain.Entities.Cart", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("JoiDelivery.Domain.Entities.User", b =>
                {
                    b.Navigation("Cart");
                });

            modelBuilder.Entity("JoiDelivery.Domain.Entities.GroceryStore", b =>
                {
                    b.Navigation("Inventory");
                });
#pragma warning restore 612, 618
        }
    }
}
